export const NUMBER_BUTTON_CLICKED = "NUMBER_BUTTON_CLICKED" ;
export const START_BUTTON_CLICKED  = "START_BUTTON_CLICKED"  ;
export const RESET_BUTTON_CLICKED  = "RESET_BUTTON_CLICKED"  ;
export const START_COUNTDOWN       = "START_COUNTDOWN"       ;
